//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htgt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchanaInformation
    {
        public int SID { get; set; }
        public string KidName { get; set; }
        public string ParentsName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> RemainderSentOn { get; set; }
    }
}
